// <auto-generated />
using System;
using LibraryManagementSystem.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230719073117_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookEntityGenreEntity", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("BooksId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("BookEntityGenreEntity");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.AuthorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ayn",
                            LastName = "Rand"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jules",
                            LastName = "Verne"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Agatha",
                            LastName = "Christie"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "George",
                            LastName = "Orwell"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Stephen",
                            LastName = "King"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "George",
                            LastName = "Martin"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Haruki",
                            LastName = "Murakami"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int?>("BookLoanId")
                        .HasColumnType("int");

                    b.Property<int?>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PagesNumber")
                        .HasColumnType("int");

                    b.Property<string>("PictureName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookLoanId")
                        .IsUnique()
                        .HasFilter("[BookLoanId] IS NOT NULL");

                    b.HasIndex("DescriptionId")
                        .IsUnique()
                        .HasFilter("[DescriptionId] IS NOT NULL");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("WarehouseId")
                        .IsUnique();

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            DescriptionId = 1,
                            LanguageId = 4,
                            PagesNumber = 528,
                            PictureName = "we_the_living.png",
                            PublisherId = 3,
                            Title = "We the Living",
                            WarehouseId = 1,
                            Year = 1936
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            DescriptionId = 2,
                            LanguageId = 1,
                            PagesNumber = 1168,
                            PictureName = "atlas_shrugged.png",
                            PublisherId = 5,
                            Title = "Atlas Shrugged",
                            WarehouseId = 2,
                            Year = 1957
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            DescriptionId = 3,
                            LanguageId = 1,
                            PagesNumber = 302,
                            PictureName = "this_side_of_paradise.png",
                            PublisherId = 2,
                            Title = "This Side Of Paradise",
                            WarehouseId = 3,
                            Year = 1920
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            DescriptionId = 4,
                            LanguageId = 4,
                            PagesNumber = 184,
                            PictureName = "the_great_gatsby.png",
                            PublisherId = 4,
                            Title = "The Great Gatsby",
                            WarehouseId = 4,
                            Year = 1925
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            DescriptionId = 5,
                            LanguageId = 2,
                            PagesNumber = 518,
                            PictureName = "20000_leagues.png",
                            PublisherId = 3,
                            Title = "20,000 Leagues Under the Sea",
                            WarehouseId = 5,
                            Year = 1870
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            DescriptionId = 6,
                            LanguageId = 4,
                            PagesNumber = 336,
                            PictureName = "the_mysterious_island.png",
                            PublisherId = 2,
                            Title = "The Mysterious Island",
                            WarehouseId = 6,
                            Year = 1875
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            DescriptionId = 7,
                            LanguageId = 2,
                            PagesNumber = 448,
                            PictureName = "the_mighty_orinoco.png",
                            PublisherId = 3,
                            Title = "The Mighty Orinoco",
                            WarehouseId = 7,
                            Year = 1898
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            DescriptionId = 8,
                            LanguageId = 4,
                            PagesNumber = 288,
                            PictureName = "murder_on_the_orient_express.png",
                            PublisherId = 1,
                            Title = "Murder on the Orient Express",
                            WarehouseId = 8,
                            Year = 1934
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            DescriptionId = 9,
                            LanguageId = 1,
                            PagesNumber = 300,
                            PictureName = "and_then_there_were_none.png",
                            PublisherId = 4,
                            Title = "And Then There Were None",
                            WarehouseId = 9,
                            Year = 1939
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            DescriptionId = 10,
                            LanguageId = 4,
                            PagesNumber = 245,
                            PictureName = "the_body_in_the_library.png",
                            PublisherId = 3,
                            Title = "The Body in the Library",
                            WarehouseId = 10,
                            Year = 1942
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            DescriptionId = 11,
                            LanguageId = 1,
                            PagesNumber = 328,
                            PictureName = "1984.png",
                            PublisherId = 2,
                            Title = "1984",
                            WarehouseId = 11,
                            Year = 1949
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            DescriptionId = 12,
                            LanguageId = 1,
                            PagesNumber = 140,
                            PictureName = "animal_farm.png",
                            PublisherId = 5,
                            Title = "Animal Farm",
                            WarehouseId = 12,
                            Year = 1945
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 6,
                            DescriptionId = 13,
                            LanguageId = 4,
                            PagesNumber = 310,
                            PictureName = "misery.png",
                            PublisherId = 5,
                            Title = "Misery",
                            WarehouseId = 13,
                            Year = 1987
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            DescriptionId = 14,
                            LanguageId = 2,
                            PagesNumber = 447,
                            PictureName = "the_shining.png",
                            PublisherId = 2,
                            Title = "The Shining",
                            WarehouseId = 14,
                            Year = 1977
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 7,
                            DescriptionId = 15,
                            LanguageId = 4,
                            PagesNumber = 694,
                            PictureName = "got.png",
                            PublisherId = 1,
                            Title = "A Game of Thrones",
                            WarehouseId = 15,
                            Year = 1996
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 7,
                            DescriptionId = 16,
                            LanguageId = 1,
                            PagesNumber = 761,
                            PictureName = "a_clash_of_kings.png",
                            PublisherId = 1,
                            Title = "A Clash of Kings",
                            WarehouseId = 16,
                            Year = 1998
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 7,
                            DescriptionId = 17,
                            LanguageId = 1,
                            PagesNumber = 973,
                            PictureName = "a_sword_of_swords.png",
                            PublisherId = 1,
                            Title = "A Storm of Swords",
                            WarehouseId = 17,
                            Year = 2000
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 8,
                            DescriptionId = 18,
                            LanguageId = 3,
                            PagesNumber = 389,
                            PictureName = "norwegian_wood.png",
                            PublisherId = 2,
                            Title = "Norwegian Wood",
                            WarehouseId = 18,
                            Year = 1987
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 8,
                            DescriptionId = 19,
                            LanguageId = 3,
                            PagesNumber = 928,
                            PictureName = "1q84.png",
                            PublisherId = 2,
                            Title = "1Q84",
                            WarehouseId = 19,
                            Year = 2009
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 8,
                            DescriptionId = 20,
                            LanguageId = 3,
                            PagesNumber = 607,
                            PictureName = "the_wind-up_bird_chronicle.png",
                            PublisherId = 2,
                            Title = "The Wind-Up Bird Chronicle",
                            WarehouseId = 20,
                            Year = 1997
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookGenreEntity", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("BookGenres", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 2,
                            GenreId = 8
                        },
                        new
                        {
                            BookId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            BookId = 4,
                            GenreId = 4
                        },
                        new
                        {
                            BookId = 5,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 6,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 7,
                            GenreId = 5
                        },
                        new
                        {
                            BookId = 8,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 9,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 10,
                            GenreId = 6
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 9
                        },
                        new
                        {
                            BookId = 11,
                            GenreId = 10
                        },
                        new
                        {
                            BookId = 12,
                            GenreId = 10
                        },
                        new
                        {
                            BookId = 13,
                            GenreId = 11
                        },
                        new
                        {
                            BookId = 14,
                            GenreId = 11
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 8
                        },
                        new
                        {
                            BookId = 15,
                            GenreId = 10
                        },
                        new
                        {
                            BookId = 16,
                            GenreId = 8
                        },
                        new
                        {
                            BookId = 16,
                            GenreId = 10
                        },
                        new
                        {
                            BookId = 17,
                            GenreId = 8
                        },
                        new
                        {
                            BookId = 17,
                            GenreId = 10
                        },
                        new
                        {
                            BookId = 18,
                            GenreId = 3
                        },
                        new
                        {
                            BookId = 19,
                            GenreId = 7
                        },
                        new
                        {
                            BookId = 20,
                            GenreId = 8
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.DescriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Descriptions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 0,
                            Description = "We the Living is not a story of politics, but of the men and women who have to struggle for existence behind the Red banners and slogans. It is a picture of what those slogans do to human beings. What happens to the defiant ones? What happens to those who succumb?\r\n\r\nAgainst a vivid panorama of political revolution and personal revolt, Ayn Rand shows what the theory of socialism means in practice. "
                        },
                        new
                        {
                            Id = 2,
                            BookId = 0,
                            Description = "Who is John Galt? When he says that he will stop the motor of the world, is he a destroyer or a liberator? Why does he have to fight his battles not against his enemies but against those who need him most? Why does he fight his hardest battle against the woman he loves?\r\n\r\nYou will know the answer to these questions when you discover the reason behind the baffling events that play havoc with the lives of the amazing men and women in this book. You will discover why a productive genius becomes a worthless playboy...why a great steel industrialist is working for his own destruction...why a composer gives up his career on the night of his triumph...why a beautiful woman who runs a transcontinental railroad falls in love with the man she has sworn to kill."
                        },
                        new
                        {
                            Id = 3,
                            BookId = 0,
                            Description = "\"I don't want to repeat my innocence. I want the pleasure of losing it again.\"\r\nYoung Amory Blaine, who is convinced he has an exceptionally promising future, finishes boarding school and attends Princeton. At university, Amory is an indifferent student, preferring instead to fall in and out of love, and cheerfully immersing himself in a glitzy world of excessive drinking and casual liaisons.\r\nWritten at the tender age of twenty-three, F. Scott Fitzgerald's first novel mirrors some of his own experiences at Princeton University. This romance of the early Jazz Age is a commentary on how love can be affected by money and social status."
                        },
                        new
                        {
                            Id = 4,
                            BookId = 0,
                            Description = "\"The Great Gatsby\" is a classic novel written by F. Scott Fitzgerald. Set in the lavish and glamorous world of 1920s America, the story followsJay Gatsby, a mysterious and enigmatic millionaire, through the eyes of Nick Carraway, a young Midwesterner who becomes Gatsby's neighbor. The book delves into themes of love, wealth, decadence, and the illusion of the American Dream."
                        },
                        new
                        {
                            Id = 5,
                            BookId = 0,
                            Description = "When an unidentified monster threatens international shipping, French oceanographer Pierre Aronnax and his unflappable assistant Conseil join an expedition organized by the US Navy to hunt down and destroy the menace. After months of fruitless searching, they finally grapple with their quarry, but Aronnax, Conseil, and the brash Canadian harpooner Ned Land are thrown overboard in the attack, only to find that the “monster” is actually a futuristic submarine, the Nautilus, commanded by a shadowy, mystical, preternaturally imposing man who calls himself Captain Nemo. Thus begins a journey of 20,000 leagues—nearly 50,000 miles—that will take Captain Nemo, his crew, and these three adventurers on a journey of discovery through undersea forests, coral graveyards, miles-deep trenches, and even the sunken ruins of Atlantis. "
                        },
                        new
                        {
                            Id = 6,
                            BookId = 0,
                            Description = "A stolen hot air balloon lands an unlikely crew on a mysterious island far from everything they know in this action-packed Jules Verne classic—nowwith an arresting new look!\r\n\r\nFive prisoners of war steal a hot air balloon and escape capture in Virginia during the American Civil War. They fly for several thousand miles before a storm forces them to crash land on an unknown island in the Pacific. There, the marooned men must work together to pool all their knowledge and skill if they wish to survive.\r\n\r\nBut the island has its secrets, and the castaways discover it’s not as deserted as they thought. A mysterious figure has been watching them. Does it bring salvation or even more danger?"
                        },
                        new
                        {
                            Id = 7,
                            BookId = 0,
                            Description = "The Mighty Orinoco tells the story of a young man's search for his father along the then-uncharted Orinoco River of Venezuela. The text contains all the ingredients of a classic Verne scientific-adventure tale: exploration and discovery, humor and drama, dastardly villains and intrepid heroes, and a host of near-fatal encounters with crocodiles, jungle fever, Indians and outlaws ― all set in a wonderfully exotic locale. The Mighty Orinoco also includes a unique twist that will appeal to feminists ― readers will need to discover it for themselves."
                        },
                        new
                        {
                            Id = 8,
                            BookId = 0,
                            Description = "Just after midnight, a snowdrift stops the famous Orient Express in its tracks as it travels through the mountainous Balkans. The luxurious train is surprisingly full for the time of the year but, by the morning, it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside.\r\n\r\nOne of the passengers is none other than detective Hercule Poirot. On vacation.\r\n\r\nIsolated and with a killer on board, Poirot must identify the murderer—in case he or she decides to strike again."
                        },
                        new
                        {
                            Id = 9,
                            BookId = 0,
                            Description = "First, there were ten—a curious assortment of strangers summoned as weekend guests to a little private island off the coast of Devon. Their host, an eccentric millionaire unknown to all of them, is nowhere to be found. All that the guests have in common is a wicked past they're unwilling to reveal—and a secret that will seal their fate. For each has been marked for murder. A famous nursery rhyme is framed and hung in every room of the mansion.\n\nWhen they realize that murders are occurring as described in the rhyme, terror mounts. One by one they fall prey. Before the weekend is out, there will be none. Who has choreographed this dastardly scheme? And who will be left to tell the tale? Only the dead are above suspicion."
                        },
                        new
                        {
                            Id = 10,
                            BookId = 0,
                            Description = "It’s seven in the morning. The Bantrys wake to find the body of a young woman in their library. She is wearing evening dress and heavy make-up, which is now smeared across her cheeks.\r\n\r\nBut who is she? How did she get there? And what is the connection with another dead girl, whose charred remains are later discovered in an abandoned quarry?\r\n\r\nThe respectable Bantrys invite Miss Marple to solve the mystery… before tongues start to wag."
                        },
                        new
                        {
                            Id = 11,
                            BookId = 0,
                            Description = "The new novel by George Orwell is the major work towards which all his previous writing has pointed. Critics have hailed it as his \"most solid, most brilliant\" work. Though the story of Nineteen Eighty-Four takes place thirty-five years hence, it is in every sense timely. The scene is London, where there has been no new housing since 1950 and where the city-wide slums are called Victory Mansions. Science has abandoned Man for the State. As every citizen knows only too well, war is peace."
                        },
                        new
                        {
                            Id = 12,
                            BookId = 0,
                            Description = "A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned –a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible."
                        },
                        new
                        {
                            Id = 13,
                            BookId = 0,
                            Description = "Paul Sheldon. He's a bestselling novelist who has finally met his biggest fan. Her name is Annie Wilkes and she is more than a rabid reader - she is Paul's nurse, tending his shattered body after an automobile accident. But she is also his captor, keeping him prisoner in her isolated house."
                        },
                        new
                        {
                            Id = 14,
                            BookId = 0,
                            Description = "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister. And the only one to notice the strange and terrible forces gathering around the Overlook is Danny Torrance, a uniquely gifted five-year-old."
                        },
                        new
                        {
                            Id = 15,
                            BookId = 0,
                            Description = "Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom’s protective Wall. To the south, the king’s powers are failing—his most trusted adviser dead under mysterious circumstances and his enemies emerging from the shadows of the throne. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the frozen land they were born to. Now Lord Eddard Stark is reluctantly summoned to serve as the king’s new Hand, an appointment that threatens to sunder not only his family but the kingdom itself."
                        },
                        new
                        {
                            Id = 16,
                            BookId = 0,
                            Description = "A comet the color of blood and flame cuts across the sky. Two great leaders—Lord Eddard Stark and Robert Baratheon—who hold sway over an age of enforced peace are dead, victims of royal treachery. Now, from the ancient citadel of Dragonstone to the forbidding shores of Winterfell, chaos reigns. Six factions struggle for control of a divided land and the Iron Throne of the Seven Kingdoms, preparing to stake their claims through tempest, turmoil, and war.\r\n\r\nIt is a tale in which brother plots against brother and the dead rise to walk in the night. Here a princess masquerades as an orphan boy; a knight of the mind prepares a poison for a treacherous sorceress; and wild men descend from the Mountains of the Moon to ravage the countryside. Against a backdrop of incest and fratricide, alchemy and murder, victory may go to the men and women possessed of the coldest steel...and the coldest hearts. For when kings clash, the whole land trembles."
                        },
                        new
                        {
                            Id = 17,
                            BookId = 0,
                            Description = "Of the five contenders for power, one is dead, another in disfavor, and still the wars rage as alliances are made and broken. Joffrey sits on the Iron Throne, the uneasy ruler of the Seven Kingdoms. His most bitter rival, Lord Stannis, stands defeated and disgraced, victim of the sorceress who holds him in her thrall. Young Robb still rules the North from the fortress of Riverrun. Meanwhile, making her way across a blood-drenched continent is the exiled queen, Daenerys, mistress of the only three dragons still left in the world. And as opposing forces manoeuver for the final showdown, an army of barbaric wildlings arrives from the outermost limits of civilization, accompanied by a horde of mythical Others—a supernatural army of the living dead whose animated corpses are unstoppable. As the future of the land hangs in the balance, no one will rest until the Seven Kingdoms have exploded in a veritable storm of swords..."
                        },
                        new
                        {
                            Id = 18,
                            BookId = 0,
                            Description = "Toru, a quiet and preternaturally serious young college student in Tokyo, is devoted to Naoko, a beautiful and introspective young woman, but their mutual passion is marked by the tragic death of their best friend years before. Toru begins to adapt to campus life and the loneliness and isolation he faces there, but Naoko finds the pressures and responsibilities of life unbearable. As she retreats further into her own world, Toru finds himself reaching out to others and drawn to a fiercely independent and sexually liberated young woman.\r\n\r\nA magnificent blending of the music, the mood, and the ethos that was the sixties with the story of one college student's romantic coming of age, Norwegian Wood brilliantly recaptures a young man's first, hopeless, and heroic love."
                        },
                        new
                        {
                            Id = 19,
                            BookId = 0,
                            Description = "A young woman named Aomame follows a taxi driver’s enigmatic suggestion and begins to notice puzzling discrepancies in the world around her. She has entered, she realizes, a parallel existence, which she calls 1Q84 —“Q is for ‘question mark.’ A world that bears a question.” Meanwhile, an aspiring writer named Tengo takes on a suspect ghostwriting project. He becomes so wrapped up with the work and its unusual author that, soon, his previously placid life begins to come unraveled."
                        },
                        new
                        {
                            Id = 20,
                            BookId = 0,
                            Description = "Japan's most highly regarded novelist now vaults into the first ranks of international fiction writers with this heroically imaginative novel, which is at once a detective story, an account of a disintegrating marriage, and an excavation of the buried secrets of World War II.\r\n\r\nIn a Tokyo suburb a young man named Toru Okada searches for his wife's missing cat. Soon he finds himself looking for his wife as well in a netherworld that lies beneath the placid surface of Tokyo. As these searches intersect, Okada encounters a bizarre group of allies and antagonists: a psychic prostitute; a malevolent yet mediagenic politician; a cheerfully morbid sixteen-year-old-girl; and an aging war veteran who has been permanently changed by the hideous things he witnessed during Japan's forgotten campaign in Manchuria."
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.GenreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bildungsroman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tragedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dystopian"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Political"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Psychological"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.LanguageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Name = "French"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ukrainian"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.PublisherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AST"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ZNANNIA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Signet"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fingerprint! Publishing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dutton"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.WarehouseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Warehouse", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 0,
                            Price = 4.49m,
                            Quantity = 16
                        },
                        new
                        {
                            Id = 2,
                            BookId = 0,
                            Price = 24.11m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 3,
                            BookId = 0,
                            Price = 15.04m,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 4,
                            BookId = 0,
                            Price = 11.61m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 5,
                            BookId = 0,
                            Price = 12.10m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 6,
                            BookId = 0,
                            Price = 2.29m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 7,
                            BookId = 0,
                            Price = 14.89m,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 8,
                            BookId = 0,
                            Price = 3.66m,
                            Quantity = 7
                        },
                        new
                        {
                            Id = 9,
                            BookId = 0,
                            Price = 6.16m,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 10,
                            BookId = 0,
                            Price = 8.32m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 11,
                            BookId = 0,
                            Price = 11.22m,
                            Quantity = 35
                        },
                        new
                        {
                            Id = 12,
                            BookId = 0,
                            Price = 3.96m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 13,
                            BookId = 0,
                            Price = 9.15m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 14,
                            BookId = 0,
                            Price = 12.49m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 15,
                            BookId = 0,
                            Price = 20.99m,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 16,
                            BookId = 0,
                            Price = 14.38m,
                            Quantity = 13
                        },
                        new
                        {
                            Id = 17,
                            BookId = 0,
                            Price = 12.99m,
                            Quantity = 4
                        },
                        new
                        {
                            Id = 18,
                            BookId = 0,
                            Price = 8.49m,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 19,
                            BookId = 0,
                            Price = 15.99m,
                            Quantity = 6
                        },
                        new
                        {
                            Id = 20,
                            BookId = 0,
                            Price = 19.20m,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookLoanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("LibrarianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId");

                    b.HasIndex("StudentId");

                    b.ToTable("BookLoans", (string)null);
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.LibrarianEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Librarians", (string)null);
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.StudentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PictureName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("BookEntityGenreEntity", b =>
                {
                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", b =>
                {
                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.AuthorEntity", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookLoanEntity", "BookLoan")
                        .WithOne("Book")
                        .HasForeignKey("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", "BookLoanId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.DescriptionEntity", "Description")
                        .WithOne("Book")
                        .HasForeignKey("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", "DescriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.LanguageEntity", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.PublisherEntity", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.WarehouseEntity", "Warehouse")
                        .WithOne("Book")
                        .HasForeignKey("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", "WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BookLoan");

                    b.Navigation("Description");

                    b.Navigation("Language");

                    b.Navigation("Publisher");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookGenreEntity", b =>
                {
                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.BookEntities.GenreEntity", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookLoanEntity", b =>
                {
                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.LibrarianEntity", "Librarian")
                        .WithMany("BookLoans")
                        .HasForeignKey("LibrarianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.StudentEntity", "Student")
                        .WithMany("BookLoans")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Librarian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.StudentEntity", b =>
                {
                    b.HasOne("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.CityEntity", "City")
                        .WithMany("Students")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("City");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.AuthorEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.BookEntity", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.DescriptionEntity", b =>
                {
                    b.Navigation("Book")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.GenreEntity", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.LanguageEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.PublisherEntity", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookEntities.WarehouseEntity", b =>
                {
                    b.Navigation("Book")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.BookLoanEntity", b =>
                {
                    b.Navigation("Book")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.LibrarianEntity", b =>
                {
                    b.Navigation("BookLoans");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.CityEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("LibraryManagementSystem.BLL.Models.Entities.StudentEntities.StudentEntity", b =>
                {
                    b.Navigation("BookLoans");
                });
#pragma warning restore 612, 618
        }
    }
}
